# utils/constants.py
"""Project-wide constants to eliminate magic numbers."""

# Time constants (in seconds)
SECONDS_PER_DAY = 86400
DAYS_IN_MONTH = 30
MONTH_IN_SECONDS = SECONDS_PER_DAY * DAYS_IN_MONTH  # 86400 * 30

# Redis expiration times
REDIS_USER_CONTEXT_EXPIRE = MONTH_IN_SECONDS  # 30 days
REDIS_SHORT_EXPIRE = 300  # 5 minutes
REDIS_HISTORY_EXPIRE = 7 * SECONDS_PER_DAY  # 7 days

# LLM Configuration
DEFAULT_TEMPERATURE = 0.7
DEFAULT_MAX_TOKENS = 150
MAX_CONTEXT_SIZE_KB = 100

# Message limits
MAX_HISTORY_LENGTH = 50
RECENT_MESSAGES_COUNT = 10
TEMPORAL_SUMMARY_COUNT = 40

# UI/UX Constants
TYPING_DEBOUNCE_DELAY = 60  # seconds
HEALTH_CHECK_INTERVAL = 300  # 5 minutes
REVIEW_QUEUE_WARNING_THRESHOLD = 150  # messages

# Database limits
MAX_REVIEWER_NOTES_LENGTH = 1000
MAX_USER_MESSAGE_LENGTH = 4000

# Entity Resolution
DEFAULT_ENTITY_CACHE_SIZE = 1000
DEFAULT_ENTITY_WARM_UP_DIALOGS = 100

# Constitution
CONSTITUTION_VERSION = "4.2"
MAX_RISK_SCORE = 1.0
MIN_RISK_SCORE = 0.0